<?php

__('This block displays a carousel of properties', 'immotolbox-connect');
__('ImmoToolBox Property Carousel', 'immotolbox-connect');
__('CSS', 'immotolbox-connect');
__('Yes', 'immotolbox-connect');
__('No', 'immotolbox-connect');
__('Javascript', 'immotolbox-connect');
__('Include Bootstrap', 'immotolbox-connect');
__('Featured', 'immotolbox-connect');
__('Rooms', 'immotolbox-connect');
__('Default values :', 'immotolbox-connect');
__('Hidden fields :', 'immotolbox-connect');
__('Pre-filled values', 'immotolbox-connect');
__('Submit', 'immotolbox-connect');
__('Hidden fields', 'immotolbox-connect');
__('Horizontal', 'immotolbox-connect');
__('Vertical', 'immotolbox-connect');
__('Format', 'immotolbox-connect');
__('This block displays a search engine', 'immotolbox-connect');
__('ImmoToolBox Property Search', 'immotolbox-connect');
__('Other settings :', 'immotolbox-connect');
__('Ordering :', 'immotolbox-connect');
__('Agency', 'immotolbox-connect');
__('Num. rooms', 'immotolbox-connect');
__('Building', 'immotolbox-connect');
__('District', 'immotolbox-connect');
__('City', 'immotolbox-connect');
__('Country', 'immotolbox-connect');
__('Transaction', 'immotolbox-connect');
__('Search values :', 'immotolbox-connect');
__('Other settings', 'immotolbox-connect');
__('Desc', 'immotolbox-connect');
__('Asc', 'immotolbox-connect');
__('Direction', 'immotolbox-connect');
__('Area', 'immotolbox-connect');
__('Price', 'immotolbox-connect');
__('Date', 'immotolbox-connect');
__('Order', 'immotolbox-connect');
__('Ordering', 'immotolbox-connect');
__('Agency ID', 'immotolbox-connect');
__('Featured properties', 'immotolbox-connect');
__('Min. area', 'immotolbox-connect');
__('Max. price', 'immotolbox-connect');
__('Nb. rooms', 'immotolbox-connect');
__('Building ID', 'immotolbox-connect');
__('District ID', 'immotolbox-connect');
__('City ID', 'immotolbox-connect');
__('Country Code', 'immotolbox-connect');
__('Properties for rent', 'immotolbox-connect');
__('Properties for sale', 'immotolbox-connect');
__('Type', 'immotolbox-connect');
__('Filter properties', 'immotolbox-connect');
__('This block displays a list of properties', 'immotolbox-connect');
__('ImmoToolBox Property Listing', 'immotolbox-connect');
__('Documentation can be found on the <a href="%s" target="_blank">plugin page</a>.', 'immotolbox-connect');
__('https://www.immotoolbox.com/', 'immotolbox-connect');
__('ITB Connect', 'immotolbox-connect');
__('Clear cache', 'immotolbox-connect');
__('file(s) in cache', 'immotolbox-connect');
__('ITB Connect API Settings', 'immotolbox-connect');
__('You can get your API settings from your <b>Integrations</b> page on ImmoToolBox.', 'immotolbox-connect');
__('Private key', 'immotolbox-connect');
__('Google Maps key', 'immotolbox-connect');
__('Detected pages', 'immotolbox-connect');
__('Other pages', 'immotolbox-connect');
__('The WordPress page used to display a property', 'immotolbox-connect');
__('The WordPress page used to display search results', 'immotolbox-connect');
__('An error happened while trying to connect to ImmoToolBox. Please double check the API Private key.', 'immotolbox-connect');
__('The connection to ImmoToolBox is established!', 'immotolbox-connect');
__('Properties available :', 'immotolbox-connect');
__('Please fill up your API keys to see the widget options.', 'immotolbox-connect');
__('Save', 'immotolbox-connect');
__('On request', 'immotolbox-connect');
__('Contact the agency', 'immotolbox-connect');
__('properties found', 'immotolbox-connect');
__('property found', 'immotolbox-connect');
__('No property found', 'immotolbox-connect');
__('Date', 'immotolbox-connect');
__('Price', 'immotolbox-connect');
__('Price on request', 'immotolbox-connect');
__('Read more...', 'immotolbox-connect');
__('Previous', 'immotolbox-connect');
__('Next', 'immotolbox-connect');
__('No properties found', 'immotolbox-connect');
__('Information', 'immotolbox-connect');
__('Building', 'immotolbox-connect');
__('District', 'immotolbox-connect');
__('City', 'immotolbox-connect');
__('Country', 'immotolbox-connect');
__('Living area', 'immotolbox-connect');
__('Living', 'immotolbox-connect');
__('Area', 'immotolbox-connect');
__('sqm', 'immotolbox-connect');
__('Terrace area', 'immotolbox-connect');
__('Terrace', 'immotolbox-connect');
__('Land area', 'immotolbox-connect');
__('Land', 'immotolbox-connect');
__('Garden area', 'immotolbox-connect');
__('Garden', 'immotolbox-connect');
__('Total area', 'immotolbox-connect');
__('Total', 'immotolbox-connect');
__('Rooms', 'immotolbox-connect');
__('Bedrooms', 'immotolbox-connect');
__('Bathrooms', 'immotolbox-connect');
__('Baths', 'immotolbox-connect');
__('Parkings', 'immotolbox-connect');
__('Box', 'immotolbox-connect');
__('Cellars', 'immotolbox-connect');
__('Situation', 'immotolbox-connect');
__('Approximative situation', 'immotolbox-connect');
__('Property not found', 'immotolbox-connect');
__('The requested property cannot be found', 'immotolbox-connect');
__('All', 'immotolbox-connect');
__('Type', 'immotolbox-connect');
__('For sale', 'immotolbox-connect');
__('To rent', 'immotolbox-connect');
__('Max price', 'immotolbox-connect');
__('Min living area', 'immotolbox-connect');
__('Search', 'immotolbox-connect');